services:
  postgres-db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - habit-tracker-network

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - habit-tracker-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit-tracker-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER:-habit-tracker-api}
      JWT_EXPIRATION_DURATION: ${JWT_EXPIRATION_DURATION:-PT10M}
      REFRESH_TOKEN_EXPIRATION_DURATION: ${REFRESH_TOKEN_EXPIRATION_DURATION:-P7D}
      HABIT_RETENTION_PERIOD: ${HABIT_RETENTION_PERIOD:-P14D}
      USER_RETENTION_PERIOD: ${USER_RETENTION_PERIOD:-P14D}
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - habit-tracker-network

  frontend:
    image: shenol10/habit-tracker-frontend:1.0.0
    container_name: habit-tracker-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - app
    networks:
      - habit-tracker-network

networks:
  habit-tracker-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: