name: CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Check if formatting is needed
        id: check-format
        run: |
          ./gradlew spotlessCheck || echo "format_needed=true" >> $GITHUB_OUTPUT
      
      - name: Apply Spotless formatting
        if: steps.check-format.outputs.format_needed == 'true'
        run: ./gradlew spotlessApply
      
      - name: Commit formatting changes
        id: commit
        if: steps.check-format.outputs.format_needed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: apply spotless formatting'
          branch: ${{ github.head_ref }}

      - name: Set output
        id: output
        run: |
          if [ "${{ steps.check-format.outputs.format_needed }}" == "true" ]; then
            echo "formatting_applied=true" >> $GITHUB_OUTPUT
          else
            echo "formatting_applied=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build and Test
    needs: format
    runs-on: ubuntu-latest
    # Only run this job if we didn't apply formatting or if we're on main branch
    # This avoids building the non-formatted code when formatting was applied
    if: needs.format.outputs.formatting_applied == 'false' || github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build with Gradle
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0