name: Spotless Format on PR

on:
  pull_request:
    branches:
      - main # Or your default branch, e.g., 'master', 'develop'

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Check for changes
        id: git_diff
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          # Check if there are any changes after running spotlessApply
          if git diff --quiet --cached; then
            echo "::set-output name=changes_made::false"
          else
            echo "::set-output name=changes_made::true"
          fi
        shell: bash

      - name: Commit and Push Formatted Code
        if: steps.git_diff.outputs.changes_made == 'true'
        run: |
          git commit -m "Auto-format code with Spotless [skip ci]"
          git push
        shell: bash